import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import useSWR from 'swr'
import { useSession, signIn, signOut } from "next-auth/react"

const inter = Inter({subsets: ['latin']})

const fetcher = (...args) => fetch(...args).then((res) => res.json())

export default function Home() {
  const {data: session} = useSession()

  const {data, error, isLoading} = useSWR('https://coding-challenge-be.vercel.app/api/index', fetcher)

  if (error) return <main className={styles.main}><h1>failed to load</h1></main>
  if (isLoading) return <main className={styles.main}><div>loading...</div></main>

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <div>
        {session && session.user ? (
          <h2>Eth price {data.data.price}   <button onClick={() => signOut()}>Sign out</button></h2>
        ): (<h2>Please sigin   <button onClick={() => signIn()}>Sign in</button></h2>)
}        </div>
      </main>
    </>
  )
}
